apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEF6TURJeApNalV3TURKYUZ3MDBOVEF6TURJeE1qVXdNREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDdndtWVd0QlUwU0pFWmlqcWV4c1R3dS8rZDkwYitlZ0FRRTExc21TekwweVAzalpTVQpMbnJyMlJ3bDVyN2JSUURLUGNKcUdHNHhSdXE1aUtWRXRmcW16ZlRyVmlmRVo5SElEc0FjaUlRZlZTWENpd2dpClFBcUNYQVNBb21wK0RjN1ljQVFGSlAwMm5ZLzdXK0N1R1NHdlBDMmFFbEZiNjd5eTcwT2NMN1duMFIvZS9kazcKeUF6VGIweHFweW1zOWxZbjM0NnBhdnQzQUc5b3RSZ20zcXpaWWUrMC9nL3I2WURTUU1WL0FqZEhnK3VzeXFZOQppVWZCejBnd1BiR05ZWlRQaFRPd0g3dG0wU1pKUnYwd1FaeDhWQ3RoWk5QS3lzbmZTL0RKc0hlWXgxR0hWREFHCnMzQVRnYTNKVHdMS3haTmJoK2UreHl1OFJZNWNTSUZ4ckFQVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlE3Smh1Z25YVHB5dmZNL3RRNQpUSTR1QzA5REREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGRFBDWXFRMllpaUpiY01OSitGdGs0ZW1DWkNqCnhSd25tcXRydUYrR01oejNpeTk1bGU3MEhCVnRTRnQ0aTNOdUl4cWJOVlNqN1A3ZG5OQUNZM0U0OGZmTWYrY2wKVEY1YSs3M1labEZRcVd6dkRWMklPbzNDVUdibHBNdkVVZWxOeWdnTXA5YUxlTzNKTEgrdVQ2R2tvRzB0VXhCdgpKbm9acTVkTDUxSXpCL2NPNjlucWtrV1NndjVxS2Q4enBteWh1bC9QcXljTXV3SERpRlJhSnJxd3NRRk5oNi9ICnc1cVJCaURUMVBGTkozbHdhVlNsV1R1MFNNT25Tc0dScktWUEc5ZHplaDNPVldhUm42R2VGZ3hBL0xSM09DSG4KZzFpbzNWSktxWXZtRldLK3U1NGUyNGhJeExRU2Z2aFY5UGw3QnlyZFZMSmY2LytEOFRYQVhtRmo1UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://00dd0ecb-d7be-4c96-93ab-eba9754ca005.k8s.ondigitalocean.com
  name: do-blr1-k8s-1-32-1-do-0-blr1-1740919768473
contexts:
- context:
    cluster: do-blr1-k8s-1-32-1-do-0-blr1-1740919768473
    user: do-blr1-k8s-1-32-1-do-0-blr1-1740919768473-admin
  name: do-blr1-k8s-1-32-1-do-0-blr1-1740919768473
current-context: do-blr1-k8s-1-32-1-do-0-blr1-1740919768473
kind: Config
preferences: {}
users:
- name: do-blr1-k8s-1-32-1-do-0-blr1-1740919768473-admin
  user:
    token: dop_v1_608ec8eea24d898c51c096612bd106f846408cd583dfa4e1ca1e6a9658ecc2b9
