# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: consumer-service-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | b64enc }}
  KAFKA_USERNAME: {{ .Values.env.KAFKA_USERNAME | b64enc }}
  KAFKA_PASSWORD: {{ .Values.env.KAFKA_PASSWORD | b64enc }}
  KAFKA_BROKER: {{ .Values.env.KAFKA_BROKER | b64enc }}